spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/task-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgresPlusDialect
      ddl-auto: create
jwt:
  secret-key: 'secret-key'
  token:
    prefix: 'Bearer '
    expiration-time: 43200000 # 12 hours